#!/bin/sh
#/etc/init.d/watchdog: start watchdog daemon.

### BEGIN INIT INFO
# Provides:          door-system
# Short-Description: Start door system daemon
# Required-Start:    $all
# Required-Stop:     $all
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin/

test -x /usr/local/sbin/door-system || exit 0

NAME=door-system
DAEMON=/usr/local/sbin/door-system
DESC="NFC Door System"
STOP_RETRY_SCHEDULE='TERM/10/forever/KILL/1'
LOGFILE=/var/log/door-system.log
# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
	# Unconditionally start watchdog daemon because we want to run it even
	# if wd_keepalive wasn't running
	log_begin_msg "Starting door-system daemon..."
	start-stop-daemon --start --quiet -b -m -p /var/run/$NAME.pid \
              --exec $DAEMON -- 
	log_end_msg $?
    ;;

  stop)
	log_begin_msg "Stopping door-system daemon..."
	start-stop-daemon --stop --quiet --retry $STOP_RETRY_SCHEDULE \
	    --pidfile /var/run/$NAME.pid
	log_end_msg $?
    ;;

  status)
    status_of_proc "$DAEMON" door-system
    ;;

  *)
    echo "Usage: /etc/init.d/door-system {start|stop}"
    exit 1

esac

exit 0
